//! Machine-readable release facts (Phase 3B, pipeline step 2).
//!
//! Facts are operator/tooling state — not a signed protocol object. Every
//! fact is computed from the **final assembled package**: the package
//! size/SHA-256 come from the final file bytes, and the two managed-EXE
//! facts are read out of the *validated archive itself*, never guessed from
//! pre-package build outputs.

use std::path::Path;

use desktop_todo_maintenance::package_zip::validate_archive;
use desktop_todo_update_core::{identity_filename, InstallIdentity, APP_ID, CLIENT_PLATFORM, SUPPORTED_UPDATER_PROTOCOL};

use crate::assemble::{hash_file, validated_entry_facts};
use crate::{ReleaseMode, PipelineError};

/// Facts for one managed executable, exactly the two fixed identities.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct InstallFileFact {
    pub identity: String,
    pub filename: String,
    pub size: u64,
    pub sha256_hex: String,
}

/// The complete release fact set for one staging run.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ReleaseFacts {
    pub mode: ReleaseMode,
    /// Final package filename as published (and carried into the manifest).
    pub package_filename: String,
    pub package_size: u64,
    pub package_sha256_hex: String,
    /// The two frozen runtime identities, in manifest order (main first).
    pub install_files: [InstallFileFact; 2],
    /// The release target version (validated frozen grammar).
    pub target_version: String,
    pub app_id: String,
    pub updater_protocol: u32,
    pub platform: String,
    /// Filled by the manifest step: SHA-256 of the exact generated bytes.
    pub manifest_sha256: Option<String>,
    /// Filled by the signing step: the envelope's key id (public fact).
    pub envelope_key_id: Option<String>,
    /// The exact canonical build commands recorded for provenance (§20);
    /// display strings only, the pipeline never builds.
    pub build_commands: [&'static str; 2],
}

/// The frozen canonical build contract (display facts only).
pub const CANONICAL_BUILD_COMMANDS: [&str; 2] = [
    "pnpm tauri build --no-bundle",
    "cargo build --release -p desktop-todo-maintenance --manifest-path src-tauri/Cargo.toml",
];

/// Compute the release facts from the final package file.
///
/// `version` must already be validated against the frozen grammar; the
/// package filename convention `desktop-todo-widget-v{version}-windows-x64.zip`
/// is the frozen example shape carried by every protocol document and release
/// record (the protocol freezes agreement, not grammar, and the updater
/// matches the package asset by exact signed-manifest filename — never by
/// parsing this name).
pub fn compute_facts(
    package_path: &Path,
    mode: ReleaseMode,
    target_version: &str,
) -> Result<ReleaseFacts, PipelineError> {
    let (package_size, package_sha256_hex) = hash_file(package_path)?;
    let package_filename = package_path
        .file_name()
        .map(|name| name.to_string_lossy().to_string())
        .ok_or_else(|| PipelineError::Facts {
            detail: "package path has no file name".to_string(),
        })?;

    // Read the two managed executables out of the validated archive itself.
    let file = std::fs::File::open(package_path).map_err(|e| PipelineError::Io {
        detail: e.to_string(),
    })?;
    let mut archive = validate_archive(file).map_err(|e| PipelineError::PackageValidation {
        detail: format!("{e:?}"),
    })?;
    let main = validated_entry_facts(&mut archive, identity_filename(InstallIdentity::MainExecutable))?;
    let helper =
        validated_entry_facts(&mut archive, identity_filename(InstallIdentity::MaintenanceHelper))?;

    Ok(ReleaseFacts {
        mode,
        package_filename,
        package_size,
        package_sha256_hex,
        install_files: [
            InstallFileFact {
                identity: "mainExecutable".to_string(),
                filename: identity_filename(InstallIdentity::MainExecutable).to_string(),
                size: main.0,
                sha256_hex: main.1,
            },
            InstallFileFact {
                identity: "maintenanceHelper".to_string(),
                filename: identity_filename(InstallIdentity::MaintenanceHelper).to_string(),
                size: helper.0,
                sha256_hex: helper.1,
            },
        ],
        target_version: target_version.to_string(),
        app_id: APP_ID.to_string(),
        updater_protocol: SUPPORTED_UPDATER_PROTOCOL,
        platform: CLIENT_PLATFORM.to_string(),
        manifest_sha256: None,
        envelope_key_id: None,
        build_commands: CANONICAL_BUILD_COMMANDS,
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::assemble::assemble_package;
    use std::fs;

    fn temp_dir(label: &str) -> std::path::PathBuf {
        let dir = std::env::temp_dir().join(format!(
            "release-pipeline-facts-{}-{}-{label}",
            std::process::id(),
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap()
                .as_nanos()
        ));
        fs::create_dir_all(&dir).unwrap();
        dir
    }

    fn build_package(dir: &std::path::Path) -> std::path::PathBuf {
        let inputs_dir = dir.join("inputs");
        fs::create_dir_all(&inputs_dir).unwrap();
        let payloads = [
            ("desktop-todo-widget.exe", vec![1u8; 64]),
            ("desktop-todo-maintenance.exe", vec![2u8; 48]),
            ("install.ps1", b"install\n".to_vec()),
            ("uninstall.ps1", b"uninstall\n".to_vec()),
            ("README.md", b"r\n".to_vec()),
            ("README_ZH.md", b"rz\n".to_vec()),
            ("LICENSE", b"MIT\n".to_vec()),
            ("LICENSE_ZH.md", b"MITz\n".to_vec()),
            ("THIRD_PARTY_NOTICES.md", b"n\n".to_vec()),
        ];
        use crate::PackageInput;
        let inputs: Vec<PackageInput> = payloads
            .into_iter()
            .map(|(name, bytes)| {
                let path = inputs_dir.join(name);
                fs::write(&path, &bytes).unwrap();
                PackageInput {
                    entry_name: *desktop_todo_maintenance::package_zip::PACKAGE_ROOT_ALLOWLIST
                        .iter()
                        .find(|allowed| **allowed == name)
                        .unwrap(),
                    source: path,
                }
            })
            .collect();
        let out = dir.join("desktop-todo-widget-v1.2.0-windows-x64.zip");
        assemble_package(&inputs, &out, false).unwrap();
        out
    }


    #[test]
    fn facts_describe_the_final_package_bytes() {
        let dir = temp_dir("final");
        let package = build_package(&dir);
        let facts = compute_facts(&package, ReleaseMode::Rehearsal, "1.2.0").unwrap();

        let (size, sha) = hash_file(&package).unwrap();
        assert_eq!(facts.package_size, size);
        assert_eq!(facts.package_sha256_hex, sha);
        assert_eq!(facts.package_filename, "desktop-todo-widget-v1.2.0-windows-x64.zip");
        assert_eq!(facts.install_files.len(), 2);
        assert_eq!(facts.install_files[0].identity, "mainExecutable");
        assert_eq!(facts.install_files[0].filename, "desktop-todo-widget.exe");
        assert_eq!(facts.install_files[0].size, 64);
        assert_eq!(
            facts.install_files[0].sha256_hex,
            desktop_todo_update_core::sha256_hex(&vec![1u8; 64])
        );
        assert_eq!(facts.install_files[1].filename, "desktop-todo-maintenance.exe");
        assert_eq!(facts.install_files[1].size, 48);
        assert_eq!(facts.app_id, "net.alanfloyd.desktop");
        assert_eq!(facts.platform, "windows-x64");
        assert_eq!(facts.updater_protocol, 1);
        fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn mutation_after_facts_changes_the_verification_result() {
        let dir = temp_dir("mutate");
        let package = build_package(&dir);
        let before = compute_facts(&package, ReleaseMode::Rehearsal, "1.2.0").unwrap();

        // Tamper with one packaged EXE in place by rebuilding the archive
        // with different bytes, then facts computed from the new bytes must
        // disagree with the earlier fact set.
        let package2 = dir.join("pkg2.zip");
        fs::copy(&package, &package2).unwrap();
        // Flip one byte deep inside the archive (the ZIP central directory
        // region is size-covered; instead append-and-rebuild via a fresh
        // assembly with a changed EXE payload).
        let package3 = dir.join("pkg3.zip");
        let inputs_dir = dir.join("inputs");
        fs::write(inputs_dir.join("desktop-todo-widget.exe"), vec![1u8; 65]).unwrap();
        use crate::PackageInput;
        let inputs: Vec<PackageInput> =
            crate::assemble::canonical_inputs(&dir.join("nonexistent"), Some(&inputs_dir.join("desktop-todo-widget.exe")), Some(&inputs_dir.join("desktop-todo-maintenance.exe")))
                .into_iter()
                .map(|input| PackageInput {
                    source: if input.entry_name == "desktop-todo-widget.exe" {
                        inputs_dir.join("desktop-todo-widget.exe")
                    } else if input.entry_name == "desktop-todo-maintenance.exe" {
                        inputs_dir.join("desktop-todo-maintenance.exe")
                    } else {
                        // Write the support files into the fake repo root.
                        fs::write(&dir.join(input.entry_name), b"x\n").unwrap();
                        dir.join(input.entry_name)
                    },
                    entry_name: input.entry_name,
                })
                .collect();
        assemble_package(&inputs, &package3, false).unwrap();
        let after = compute_facts(&package3, ReleaseMode::Rehearsal, "1.2.0").unwrap();

        assert_ne!(before.package_sha256_hex, after.package_sha256_hex);
        assert_ne!(
            before.install_files[0].sha256_hex,
            after.install_files[0].sha256_hex
        );
        assert_ne!(before.package_size, after.package_size);
        let _ = package2;
        fs::remove_dir_all(&dir).ok();
    }
}
