//! Release packaging + publishing pipeline (Phase 3B operator tooling).
//!
//! This crate chains the frozen release surface end to end:
//!
//! 1. **Assemble** the canonical nine-entry flat release ZIP
//!    (`assemble.rs`) and immediately self-validate it through the single
//!    shared package validator (`desktop_todo_maintenance::package_zip`) —
//!    never a second copy of the ZIP security rules.
//! 2. **Facts** (`facts.rs`): SHA-256 + byte size of the *final* package
//!    bytes and of the two managed executables as they sit *inside the
//!    validated archive* — never guessed from pre-package sources.
//! 3. **Manifest** (`manifest.rs`): a deterministic, byte-stable
//!    schema-1 manifest generator over those facts. The generated bytes are
//!    validated with `update_core::validate_untrusted_manifest` and are then
//!    the exact bytes that get signed and served.
//! 4. **Sign** (`signing.rs`): delegation to the existing offline
//!    `desktop-todo-release-signer` — the production path runs the compiled
//!    production trust gate (which fails closed while the store is empty);
//!    the rehearsal path uses an explicitly injected TEST trust store. This
//!    crate implements no cryptography of its own.
//! 5. **Publish / read-back / mirror** (`publish.rs`): provider upload with
//!    an explicit collision/idempotence policy, byte-exact read-back
//!    verification, and cross-provider mirror consistency.
//!
//! Deliberate boundaries: this is operator tooling, not a runtime component
//! and never linked into a shipped binary. Publishing tools only ever touch
//! the public artifacts (ZIP, manifest, envelope) — the private signing seed
//! exists only inside the signer's operation lifetime and never enters this
//! crate, the network layer, or any log.

pub mod assemble;
pub mod facts;
pub mod manifest;
pub mod pipeline;
pub mod publish;
pub mod report;
pub mod signing;
#[cfg(test)]
mod publish_tests;

use std::path::{Path, PathBuf};

/// The frozen metadata asset names (protocol v1: manifest and signature
/// live outside the ZIP, as siblings of the package). Must never drift from
/// the discovery adapters (`src/updater/providers.rs`) or the signer
/// (`ENVELOPE_FILENAME`); both are pinned by tests.
pub const MANIFEST_ASSET_NAME: &str = "update-manifest.json";
pub const ENVELOPE_ASSET_NAME: &str = "update-manifest.json.sig";

/// The exact sidecar filename convention for the manual-bootstrap digest
/// check (`<package>.sha256`).
pub const SIDECAR_SUFFIX: &str = ".sha256";

/// Execution mode of a pipeline run. Recorded in `facts.json` and enforced:
/// rehearsal artifacts may touch a production provider endpoint only through
/// a release stable discovery will not select — a GitHub draft (finalize is
/// refused in rehearsal mode) or a prerelease-marked Gitee release (which
/// has no draft state) — and a staging directory's mode can never be
/// silently switched.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ReleaseMode {
    /// Real production signing (compiled production trust gate; fails closed
    /// while no key is provisioned).
    Production,
    /// Explicit TEST/REHEARSAL: test key + injected test trust store, marked
    /// outputs, isolated destinations only.
    Rehearsal,
}

impl ReleaseMode {
    pub fn as_str(&self) -> &'static str {
        match self {
            ReleaseMode::Production => "production",
            ReleaseMode::Rehearsal => "rehearsal",
        }
    }
}

/// Typed pipeline failures. Every failure maps to a distinct non-zero exit
/// code; no error value ever carries private key material (this crate never
/// sees any).
#[derive(Debug)]
pub enum PipelineError {
    Usage(String),
    /// A required package input (EXE, script, doc) is missing or unreadable.
    InputMissing { name: String, path: PathBuf, detail: String },
    /// Input resolves outside the repo root or is not a regular file.
    InputInvalid { name: String, path: PathBuf, detail: String },
    /// The staging root is unusable (not a directory, mode conflict).
    StagingInvalid { path: PathBuf, detail: String },
    /// Package assembly failed (I/O or writer error).
    Assembly { detail: String },
    /// The assembled package failed the shared validation self-check.
    PackageValidation { detail: String },
    /// A packaged EXE could not be read out of the validated archive.
    Facts { detail: String },
    /// The output already exists and no explicit overwrite was given.
    OutputCollision { path: PathBuf },
    /// Manifest generation produced bytes that fail the frozen validation.
    ManifestInvalid { detail: String },
    /// Operator-supplied version/tag/timestamp violates the frozen grammar.
    ReleaseIdentity { detail: String },
    /// The signing step failed (delegated signer error).
    Signing { detail: String, exit_code: i32 },
    /// The staging artifacts belong to a different release mode.
    ModeConflict { detail: String },
    /// Provider publish failed (transport, provider rejection).
    Publish { detail: String },
    /// Provider collision policy refused the operation (different bytes).
    PublishCollision { detail: String },
    /// Read-back verification failed (bytes/digest/verification/ZIP/EXEs).
    ReadBack { detail: String },
    /// The two providers' artifact sets disagree.
    MirrorDisagreement { detail: String },
    /// Provider token missing from the environment.
    TokenMissing { provider: &'static str, env_var: &'static str },
    /// Rehearsal artifacts may not touch a production provider endpoint.
    RehearsalSafety { detail: String },
    Io { detail: String },
}

impl PipelineError {
    /// Distinct non-zero exit codes per failure class.
    pub fn exit_code(&self) -> i32 {
        match self {
            PipelineError::Usage(_) => 2,
            PipelineError::InputMissing { .. } => 31,
            PipelineError::InputInvalid { .. } => 32,
            PipelineError::StagingInvalid { .. } => 33,
            PipelineError::Assembly { .. } => 34,
            PipelineError::PackageValidation { .. } => 35,
            PipelineError::Facts { .. } => 36,
            PipelineError::OutputCollision { .. } => 37,
            PipelineError::ManifestInvalid { .. } => 38,
            PipelineError::ReleaseIdentity { .. } => 39,
            PipelineError::Signing { exit_code, .. } => *exit_code,
            PipelineError::ModeConflict { .. } => 41,
            PipelineError::Publish { .. } => 50,
            PipelineError::PublishCollision { .. } => 51,
            PipelineError::ReadBack { .. } => 52,
            PipelineError::MirrorDisagreement { .. } => 53,
            PipelineError::TokenMissing { .. } => 54,
            PipelineError::RehearsalSafety { .. } => 55,
            PipelineError::Io { .. } => 59,
        }
    }
}

impl std::fmt::Display for PipelineError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            PipelineError::Usage(detail) => write!(f, "usage error: {detail}"),
            PipelineError::InputMissing { name, path, detail } => {
                write!(f, "required package input {name:?} missing/unreadable ({}): {detail}", path.display())
            }
            PipelineError::InputInvalid { name, path, detail } => {
                write!(f, "package input {name:?} rejected ({}): {detail}", path.display())
            }
            PipelineError::StagingInvalid { path, detail } => {
                write!(f, "staging root unusable ({}): {detail}", path.display())
            }
            PipelineError::Assembly { detail } => write!(f, "package assembly failed: {detail}"),
            PipelineError::PackageValidation { detail } => {
                write!(f, "assembled package failed the shared validation self-check: {detail}")
            }
            PipelineError::Facts { detail } => write!(f, "release facts generation failed: {detail}"),
            PipelineError::OutputCollision { path } => write!(
                f,
                "output already exists ({}); pass --overwrite to replace it",
                path.display()
            ),
            PipelineError::ManifestInvalid { detail } => {
                write!(f, "generated manifest failed the frozen validation: {detail}")
            }
            PipelineError::ReleaseIdentity { detail } => {
                write!(f, "release identity rejected: {detail}")
            }
            PipelineError::Signing { detail, .. } => write!(f, "signing failed: {detail}"),
            PipelineError::ModeConflict { detail } => write!(f, "mode conflict: {detail}"),
            PipelineError::Publish { detail } => write!(f, "provider publish failed: {detail}"),
            PipelineError::PublishCollision { detail } => {
                write!(f, "provider collision policy refused the publish: {detail}")
            }
            PipelineError::ReadBack { detail } => {
                write!(f, "read-back verification failed: {detail}")
            }
            PipelineError::MirrorDisagreement { detail } => {
                write!(f, "provider mirror disagreement: {detail}")
            }
            PipelineError::TokenMissing { provider, env_var } => write!(
                f,
                "{provider} publish requires the {env_var} environment variable (provider auth only, never logged)"
            ),
            PipelineError::RehearsalSafety { detail } => {
                write!(f, "rehearsal safety violation: {detail}")
            }
            PipelineError::Io { detail } => write!(f, "I/O failure: {detail}"),
        }
    }
}

impl std::error::Error for PipelineError {}

impl From<desktop_todo_release_signer::ToolError> for PipelineError {
    fn from(error: desktop_todo_release_signer::ToolError) -> Self {
        PipelineError::Signing {
            detail: error.to_string(),
            exit_code: error.exit_code(),
        }
    }
}

/// One packaged file input: the exact archive entry name plus its explicit
/// source path. Assembly never scans or guesses; every entry is named here.
#[derive(Debug, Clone)]
pub struct PackageInput {
    /// Exact ZIP root entry name (must be a compiled allowlist entry).
    pub entry_name: &'static str,
    /// Explicit source file for this entry.
    pub source: PathBuf,
}

/// Validate a regular-file input: must exist, be a regular file, and be
/// readable. No symlink/reparse indirection is accepted for package inputs —
/// the assembled package must embed the real bytes an operator pointed at.
pub(crate) fn check_regular_file(name: &str, path: &Path) -> Result<(), PipelineError> {
    let metadata = std::fs::metadata(path).map_err(|e| PipelineError::InputMissing {
        name: name.to_string(),
        path: path.to_path_buf(),
        detail: e.to_string(),
    })?;
    if metadata.file_type().is_symlink() {
        return Err(PipelineError::InputInvalid {
            name: name.to_string(),
            path: path.to_path_buf(),
            detail: "input is a symlink; only regular files are accepted".to_string(),
        });
    }
    #[cfg(windows)]
    {
        use std::os::windows::fs::MetadataExt;
        const FILE_ATTRIBUTE_REPARSE_POINT: u32 = 0x0400_0000;
        if metadata.file_attributes() & FILE_ATTRIBUTE_REPARSE_POINT != 0 {
            return Err(PipelineError::InputInvalid {
                name: name.to_string(),
                path: path.to_path_buf(),
                detail: "input carries a reparse point; only regular files are accepted"
                    .to_string(),
            });
        }
    }
    if !metadata.is_file() {
        return Err(PipelineError::InputInvalid {
            name: name.to_string(),
            path: path.to_path_buf(),
            detail: "input is not a regular file".to_string(),
        });
    }
    Ok(())
}

/// Atomic output publish: sibling temp file, then rename. Existing outputs
/// are never silently overwritten; with `overwrite` the destination is
/// removed before the rename.
pub(crate) fn write_output_atomic(
    path: &Path,
    bytes: &[u8],
    overwrite: bool,
) -> Result<(), PipelineError> {
    desktop_todo_release_signer::write_atomic(path, bytes, overwrite)
        .map_err(|e| match e {
            desktop_todo_release_signer::ToolError::OutputCollision { path } => {
                PipelineError::OutputCollision { path }
            }
            other => PipelineError::Io {
                detail: other.to_string(),
            },
        })
}
